### ISSUE TITLE
npm run dev issues(98% after emitting SizeLimitsPlugin)

### ISSUE THREAD

**Issue by Happytuo** [Honvid/laravel-vue-element-admin-starter#4]
我在ubuntu下建立專案後，執行npm run dev時出現了錯誤訊息如下圖所示

[https://user-images.githubusercontent.com/17357086/65478174-61a58980-debb-11e9-9fe5-c07e2b0faec8.jpg](url)

**Comment by Honvid** [comment]
![image](https://user-images.githubusercontent.com/8649968/69392956-b8d8a680-0d12-11ea-9c2e-89bf1b97cafa.png)
看上图，没看见有报错呀。

**Comment by carveybunt** [comment]
@Happytuo 大佬，您解决了吗？我现在也是遇到这个问题了
