### ISSUE TITLE
php artisan migrate

### ISSUE THREAD

**Issue by zhushimao123** [Honvid/laravel-vue-element-admin-starter#5]
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'json null, `scope` int null, `created_at` timestamp null, `updated_at` timestamp' at line 1 (SQL: create table `abilities` (`id` int unsigned not null auto_increment primary key, `name` varchar(191) not null, `title` varchar(191) null, `entity_id` int unsigned null, `entity_type` varchar(191) null, `only_owned` tinyint(1) not null default '0', `options` json null, `scope` int null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')

**Comment by Honvid** [comment]
应该是你的mysql版本不支持json格式，导致报错。
