### ISSUE TITLE
大佬，请教下，您的passport客户端管理的组件是在哪里注册呢？

### ISSUE THREAD

**Issue by carveybunt** [Honvid/laravel-vue-element-admin-starter#6]
是在element-admin的main.js里面吗？
passport的客户端管理只支持项目内部调用，所以无奈也只能讲element集成到laravel里面了。
能否借鉴下您的代码，学习学习？

**Comment by Honvid** [comment]
the components provided by `laravel/passport` are very simple, and I rewrite them myself.
